import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  scrollContainer: {
    flexGrow: 1,
  },
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#0C1824",
    minHeight: "100%",
  },
  backButton: {
    alignSelf: "flex-start",
    padding: 8,
    bottom: 120,
  },
  backButtonText: {
    color: "#00afa1ff",
    fontSize: 26,
    fontWeight: "900",
  },
  logoContainer: {
    alignItems: "center",
    marginBottom: 60,
  },
  logo: {
    width: 120,
    height: 120,
    marginBottom: 10,
  },
  appName: {
    fontSize: 24,
    fontWeight: "700",
    color: "#000000ff",
  },
  title: {
    fontSize: 32,
    fontWeight: "700",
    marginBottom: 8,
    color: "#ffffffff",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 16,
    color: "#ebebebff",
    marginBottom: 40,
    textAlign: "center",
    lineHeight: 22,
  },
  phoneNumberText: {
    fontWeight: "600",
    color: "#ecececff",
  },
  formContainer: {
    width: "100%",
    maxWidth: 400,
  },
  inputContainer: {
    marginBottom: 30,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 12,
    color: "#e6e6e6ff",
  },
  phoneInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderColor: "#ddd",
    borderWidth: 1,
    borderRadius: 12,
    backgroundColor: "#f9f9f9",
    overflow: "hidden",
  },
  countryCodeBox: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "#f0f0f0",
  },
  countryCodeText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
  separator: {
    width: 1,
    height: 30,
    backgroundColor: "#ddd",
  },
  phoneInput: {
    flex: 1,
    height: 50,
    paddingHorizontal: 16,
    fontSize: 16,
    color: "#333",
  },
  exampleText: {
    fontSize: 12,
    color: "#e2e2e2ff",
    fontStyle: "italic",
    marginLeft: 4,
    marginTop: 8,
  },
  otpContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
    width: "100%",
    maxWidth: 400,
  },
  otpInput: {
    width: 50,
    height: 50,
    borderColor: "#ddd",
    borderWidth: 1,
    borderRadius: 12,
    fontSize: 20,
    backgroundColor: "#f9f9f9",
    textAlign: "center",
  },
  otpInputFilled: {
    borderColor: "#00afa1ff",
    backgroundColor: "#fff",
  },
  demoContainer: {
    marginBottom: 20,
    padding: 10,
    backgroundColor: "#f0f8ff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#00afa1ff",
  },
  demoText: {
    fontSize: 14,
    color: "#00afa1ff",
    textAlign: "center",
    fontStyle: "italic",
  },
  resendContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 30,
  },
  resendText: {
    color: "#e9e9e9ff",
    fontSize: 14,
  },
  resendLink: {
    color: "#00afa1ff",
    fontSize: 14,
    fontWeight: "600",
  },
  resendLinkDisabled: {
    color: "#999",
  },
  button: {
    width: "100%",
    backgroundColor: "#30BCBB",
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 15,
    marginBottom: 10,
    shadowColor: "#00afa1ff",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonText: {
    color: "#ffffffff",
    fontSize: 18,
    fontWeight: "600",
  },
  signInContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 10,
  },
  signInText: {
    color: "#e4e3e3ff",
    fontSize: 14,
  },
  signInButton: {
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 6,
  },
  signInButtonText: {
    color: "#00afa1ff",
    fontSize: 14,
    fontWeight: "600",
    textDecorationLine: "underline",
  },
});
export default styles;
